### ISSUE TITLE
串UI消失バグ

### ISSUE THREAD

**Issue by 2127002** [tpu-2022-teamA/Dango#118]
## バグ内容
役の成立後、串のUIが消滅する

## 期待した結果
役の演出後に串のUIが戻ってくる

## 再現方法
団子を食べた時

**Comment by 2127002** [comment]
恐らく原因が食事演出のアニメーションなので、修正完了まで暫定的に残しておきます。

**Comment by GTM106** [comment]
#160 にてアニメーション遷移の修正を行いました。これによりこのバグは解決しているものと思われます。確認お願いします。

**Comment by 2127002** [comment]
役成立時のアニメーションが正常に動作しているのでこの不具合も解消されていることを確認しました。
