### ISSUE TITLE
急降下刺し難しすぎるバグ

### ISSUE THREAD

**Issue by 2127002** [tpu-2022-teamA/Dango#120]
## バグ内容
急降下刺しの判定が実直すぎ(あるいはバグって)ます

## 期待した結果
プレイヤー直下に設定されたガイドの範囲にある団子であれば刺せるように、レイを飛ばす、コライダーを発生させる、コライダーの瞬間的な拡張、などを推奨

## 再現方法
急降下刺しアクション時

**Comment by GTM106** [comment]
ある程度コライダーを大きくし、アニメーション遷移のバグ修正が完了したことにより容易に急降下刺しが可能になりました。確認お願いします。

**Comment by 2127002** [comment]
容易に急降下刺しが可能になったことを確認しました。

**Comment by 2127002** [comment]
急降下刺しの更なるブラッシュアップの目的でリオープンします。
現在の当たり判定をより大きくし、また同時にマーカーも拡大をお願いします。マーカーの大きさが、およそ2倍程度になるようになることが理想です。仮に刀に当たっていない問題は、着地時のエフェクトで解消することを想定します。まずは、今よりも確実に刺せるようにする方が優先事項とします。

![image](https://user-images.githubusercontent.com/104291548/206917994-71bb5f37-5c22-4880-8085-5a1c30c3cfb3.png)

**Comment by GTM106** [comment]
上記ログの通り修正完了しています。念のため確認してからのcloseをお願いします。

**Comment by 2127002** [comment]
問題なく刺せるようになったことを確認しました。良い仕事です。お疲れ様でした。
