### ISSUE TITLE
AN4Bに付随しているイベントが発生しない場合がある

### ISSUE THREAD

**Issue by GTM106** [tpu-2022-teamA/Dango#151]
## バグ内容
AN4Bについている後半2つが発生しない場合がある

## 期待した結果
発生する

## 再現方法
AN4B中に別モーションを挟む

## 推測される原因
アニメーションがそこまでたどり着いていない

**Comment by GTM106** [comment]
@2127002 アニメーション遷移のバグ修正において、AN4Bの再生終了まで別処理を挟まない仕様になっています。その修正によりこのバグは修正されているものと思われます。確認お願いします。

**Comment by 2127002** [comment]
修正を確認しました。
