### ISSUE TITLE
リトライするとリザルトが更新されない

### ISSUE THREAD

**Issue by 2127002** [tpu-2022-teamA/Dango#158]
## バグ内容
ステージをクリアした後にリトライを行うと、前のゲームの結果が残っているのか、新規プレイの結果がリザルトに反映されない。

## 期待した結果
正常なリトライ動作

## 再現方法
ステージをクリアした後にリトライを行い、再びステージをクリアする

**Comment by GTM106** [comment]
#149 と同一のバグ報告です。念の為確認お願いします。
