### ISSUE TITLE
デフォルトキーコンフィグ修正要望

### ISSUE THREAD

**Issue by 2127002** [tpu-2022-teamA/Dango#166]
小川先生と話し合った結果、視点移動と同時に行いたいアクションとして拡張表示があるという結論に至ったので、現在のデフォルトのキーコンフィグに追加でLボタンに拡張表示を割り当ててください

**Comment by GTM106** [comment]
#168 で追加完了しました。確認お願いします。

**Comment by 2127002** [comment]
完了していることを確認済み。
