### ISSUE TITLE
団子供給システム追加要望

### ISSUE THREAD

**Issue by 2127002** [tpu-2022-teamA/Dango#167]
複数のS6Nに渡る包括的な仕様のためIssuesで失礼します(最終仕様書には記載します)。
### 問題点
現在、特定の役を完成させる目的で動き、必要な色がステージ上に一つも存在しない場合に、「詰み」に近い状態が発生、それに伴うステージ上の無意味な放浪が発生します。解消方法として、再抽選マラソンがありますが、これは作業になるためゲームデザイン上は避けたいものです。一度無役で食べて、新しく役を作るのも、役作りの過程や努力を運の要素で否定する行為なのでなるべく避けたいものです。

### 解決策
ステージ上(なおかつ移動可能な範囲)に最低でも一つ以上の色が発生するような仕様に変更。ただしこの「救済措置としての団子(以後『救済団子』と呼称)」は、刺した場所で補充されるものではなく、ステージ上の無作為なエリアに上限を超えて供給されるものとする。この理由は「残りn色2つで完成する」「n色の団子はフィールドに一つしかない」という状況で、最後のn色の団子を刺した直後に、その場で不足した団子の補充として救済団子が出てしまうことを防ぐためである。

## 事前定義
- フロアデータに「侵入可能なD5」のパラメータを追加。3D5から7D5までを選択できるように。また、複数のD5を定義できるように(3D5と4D5、5D5と6D5など)。

## 突き刺し成功時に行う処理
- この処理は突き刺しが完了し、団子が消滅した後に実行する。また、通常の団子発射装置の処理による団子の供給の後に実行されるものとする。
- フロアデータを確認し、現在のD5と侵入可能なD5が一致する場合。それらのフロアに置かれてる団子の各色の総数を確認する。総数がゼロであることが確認できた場合、次の処理に移行する。
- 現在のD5と侵入可能なD5が一致するフロアデータの中から、一つを抽選する。抽選する際に、そのフロアに既に救済団子が存在する場合は再抽選を行う。再抽選が不可能な場合(全てのエリアに救済団子が存在する場合)は処理を終了する。
- 抽選されたフロアに救済団子として不足している色の団子を発射する。これはフロアの上限を超えて配置されるものとする。またこの救済団子も配置後は「侵入可能なフロアの各色の総数」に含まれる。

**Comment by GTM106** [comment]
事前定義に関しての質問です。
`また、複数のD5を定義できるように(3D5と4D5、5D5と6D5など)。`
とありますが、複数のD5を定義できるようにする意図はなんですか？
高飛びで届くようになるD5が侵入可能なD5という認識で、それ以上のD5であれば侵入可能であると示しているのでないでしょうか。

**Comment by 2127002** [comment]
例えば仮に
**「6D5以上で侵入可能なフロア」**
といった形で設定した場合、ステージが上方向に広くなった結果、最下層の3D5の侵入可能フロアの更に末端、のような場所に生成される可能性が想定されます。それでは救済措置としての機能に問題があると考え、またレベルデザインの拡張性を考慮して
**「4D5、5D5、6D5の際に侵入可能フロアとして扱うが3D5、7D5の時は侵入可能フロアとして扱わないフロア」**
のような処理をしたいので、そういう仕様の要望になっています。

**Comment by GTM106** [comment]
なるほど、侵入可能フロアというより救済供給可能フロアという認識ですね。
誤認防止のためインスペクター上も後者の表記にしようと思います。ありがとうございます。

**Comment by 2127002** [comment]
そうですね、その認識で大丈夫です。誤解を招く表現で申し訳ない。よろしくお願いします。

**Comment by 2127002** [comment]
### Discordでの回答のメモ

・各D5、あるいは全体で発射しない色があった場合、救済は無視するのか
→**現在のD5と侵入可能なD5が一致する場合、それらのフロアに置かれてる団子の各色の総数**とあるのでサンプルケースにおいて救済は発生します。

・救済可能D5に登録されているフロアの発射装置に指定色がないが、侵入可能フロアにはある場合、救済は無視するのか
・あるフロアから出ない色がある場合、そのフロアに出ない色の救済が選ばれた場合、救済は無視するのか
→救済団子は例外的にそのフロアに設定されていない色でも発射するものとします

・抽選する際に、そのフロアに既に救済団子が存在する場合は再抽選を行う、とあるが色に限らずフロアに対して1つだけなのか。1つだけなら救済の意味を成さなくなるパターン（ずっと救済をとらない）が発生すると考えられるがその対応はどうするのか
→現行の仕様では**フロアごとに1つ**と定義されています。全てのフロアに救済団子が飽和した場合、この機能が意味を成さなくなります。この部分は暫定的に決定したものなので少し企画で話し合って仕様を決定しようと思っています、**処理を終了する**の部分に挟み込む形で派生処理が入ることになると思います。

・またこの救済団子も配置後は「侵入可能なフロアの各色の総数」に含まれる。とあるが救済団子は「部屋の団子の総数」に数えるのか。
→**侵入可能なフロアの各色の総数**には含まれますが**部屋の団子の総数**としてはカウントしません。救済団子があるフロアは部屋に設定された団子の最大数より多く団子が存在することになります。
