### ISSUE TITLE
団子刺し仕様追加要望

### ISSUE THREAD

**Issue by Harmony82** [tpu-2022-teamA/Dango#186]
団子刺し仕様追加要望
団子刺しの当たり判定は剣ではない。
キャラクター前方に角度30度、高さ1mの扇形を定義する。長さはD5によって変わる（後述）。そこが当たり判定になる。その当たり判定に触れている団子1つに2Dのアイコンでハイライトする。プレイヤーから見て3分の1以上隠れている団子は当たっていない処理。
ハイライトする団子の優先順位は1、より手前であること。2、より中心であること。
刺しボタンを押したときキャラクターはハイライトされた団子を刺す。団子に向かって特定の位置までダッシュして刺す（ダッシュの速さは、ダッシュにかかる時間を指定する。つまり距離が長いほど早くなる。仮で5分の1秒ほど。変更できるように）。特定の位置は現在のD5で変わる。剣の刃の中心に団子が来る位置までダッシュする。
ダッシュのタイミングはモーションの剣を突き刺すタイミング。
ヒットストップは棄却。

当たり判定の長さについて
当たり判定の長さはダッシュの長さ+剣の長さの2分の1になる。ダッシュの長さは後から変更できるように。当たり判定の長さはダッシュの長さ+剣の長さの2分の1になる。ダッシュの長さは後から変更できるように。仮で2mを指定。

**Comment by GTM106** [comment]
#187 で大体実装しています。新規突き刺しアニメーションの組み込みは済んでいませんが、確認お願いします。
また、ヒットストップは正しく棄却しました。ダッシュ後、団子にあたったタイミングでプレイヤーの速度を強制的に0にしているため、ヒットストップのような印象がありますが、実装していたヒットストップではありません。
刃の中心に団子が来る機能は未実装ですが、団子の速度とプレイヤーの到達速度次第で中心に近くなります。

## 未実装一覧
・高さ1mの扇形
→高さは大体1mになっていると思いますが、目算です。キレイに扇形になるものがカプセルコライダーしか見つけられなかったため、とんでもない広さ（全長8m）のコライダーになっています。
・長さはD5によって変わる
→変わりません。3D5があまりにも小さく感じたので最初からかなり広くなっています。これ以上広げたら範囲UIの占拠率があまりにも高くなってしまうことを懸念し、現状は枠組みすら作成していません。
・剣の刃の中心に団子が来る位置までダッシュする
→上記のとおり、しません。この部分は時間がかかると推測しているので、一旦仕様との齟齬がないか確認するための簡易実装になります。

**Comment by 2127002** [comment]
## 仕様追加
### 最新の処理手順の概要(既出のものを含む)
- 常時処理として、キャラクター前方30度、高さ1mの範囲内の団子をハイライトする。
1. 突き刺しボタンが押下され、突き刺しの必要条件を満たしている場合に次の処理に進む。
2. AN5を再生開始。
3. AN5の予備動作フレームを待機フレーム(可変)とし、終了まで待機。
4. 団子に向かってダッシュを行う。これは距離に関わらず一定のフレームで完了する。
5. **剣の刃の根本に団子が位置する距離**まで接近したタイミングで、団子の移動およびアニメーションを停止する。
※団子の当たり判定はアニメーションに準拠していることを想定している。そうでない場合は団子の待機アニメーションの実装と同時に変更すること。
7. 団子を**刀の子として扱い、刀の動きに追従する**ように。
8. AN5の再生終了と同時に、団子のスケールの減少アニメーションを開始。
9. 団子の**スケールが0**になるまでアニメーションを行い、**団子を消滅**させる。その後、規定の待機フレーム。
10. 刀に刺さった団子として、ポップアップ(緩急のあるスケールの上昇アニメーション)させ、同時にUIに団子が格納される処理に遷移する。

- 任意のタイミングでエフェクトを挿入できるように。
