### ISSUE TITLE
4D5でのジャンプ時に本来行けない場所に到達できる

### ISSUE THREAD

**Issue by GTM106** [tpu-2022-teamA/Dango#203]
## 概要
5D5で初めて到達できる上層に、中層部分から飛んでいくことが可能になっています。

## 想定される解決策
・ジャンプの移動速度を減らす
→これはアクションの操作感に関わるのであまりおすすめしません。
・すり抜けられる部分に壁を設置する
→景観に関わりますが、本来行けない場所にいけるよりは良いと思います
・放置する
→結局その部分のあとは6D5が必要になるので知ってる人は得する部分の仕様として残しておくのもありだと思います。1フロア増えるだけなのでぎりセーフだと思います。

## 再現方法
フロア8（Cube_007）からジャンプする

**Comment by 2127002** [comment]
対応として、壁を追加します。

**Comment by GTM106** [comment]
壁の追加が完了し次第Closeをお願いします。

**Comment by GTM106** [comment]
上記コメントでCloseをお願いしましたが、自身で修正を確認したためCloseします。
