### ISSUE TITLE
制限時間減っていないバグ

### ISSUE THREAD

**Issue by Harmony82** [tpu-2022-teamA/Dango#208]
バグ内容
制限時間が減っていません
チュートリアルでないステージでも制限時間が減っています。
　正しい処理
制限時間が存在しないのはチュートリアルのみでそれ以外は1秒に1制限時間が減ります。

**Comment by GTM106** [comment]
チュートリアルで作成した際の設定ミスです。次回の私のプルリクエストで修正予定です。
修正次第再度コメントを入れておきます

**Comment by GTM106** [comment]
#215 にて修正完了しました。

**Comment by Harmony82** [comment]
修正を確認しました。
