### ISSUE TITLE
制限時間縮小表示バグ

### ISSUE THREAD

**Issue by Harmony82** [tpu-2022-teamA/Dango#210]
バグ内容
制限時間の縮小状態でのゲージ表示が正しく表示されない場合があります。
　再現方法
団子を食べた後に縮小表示でのゲージが0になります。

**Comment by GTM106** [comment]
チュートリアルで作成した際の設定ミスです。次回の私のプルリクエストで修正予定です。
修正次第再度コメントを入れておきます

**Comment by Ryouta32** [comment]
修正しました。確認お願いします。

**Comment by Harmony82** [comment]
修正を確認しました。
