### ISSUE TITLE
制限時間拡張表示バグ

### ISSUE THREAD

**Issue by Harmony82** [tpu-2022-teamA/Dango#219]
バグ内容
チュートリアルにて拡張表示をすることで制限時間が表示されてしまうバグがあります。
　再現方法
拡張表示ボタンを押す、クエストをクリアする
　正しい処理
チュートリアルに制限時間はありません。拡張表示でも制限時間が表示されないようにしてください。

**Comment by GTM106** [comment]
@Ryouta32 が解決しています。それはまだdevelopに上がっていないと思いますが、既に解決済みです。

**Comment by Harmony82** [comment]
念のため確認後にクローズします。ありがとうございます。

**Comment by GTM106** [comment]
修正を確認したので代わりに閉じます。
