### ISSUE TITLE
エリア内最大個数超過バグ

### ISSUE THREAD

**Issue by Harmony82** [tpu-2022-teamA/Dango#220]
内部処理の状態がわかりづらい仕様なので再現方法等間違っている可能性が高いです。

　バグ内容
エリア内の団子の最大数に設定した個数を2以上超えます。

　再現方法
救済団子がトリガーだと思われます。特定の団子を食べ続けて意図的に救済させようとすると発生します。
たまに残り一個の種類の団子を食べる時に他の種類の団子が最大数を超えて出ることがあります。その後本来救済されるべき団子も出ます。この2つの団子が出るエリアと最後の一個を刺したエリアは同じ気がします。その後他のエリアでも際限なく団子が射出されます。

**Comment by GTM106** [comment]
#223 で原因とみられるものを取り除きました。また同じバグが再現したらお知らせください。

**Comment by Harmony82** [comment]
最近見ないから下げます。
