### ISSUE TITLE
クエスト内容と表記が異なる部分が存在する

### ISSUE THREAD

**Issue by GTM106** [tpu-2022-teamA/Dango#254]
## バグ内容
ステージ3におけるクエスト「急降下で2回刺す」が3回のクリアになっている。

## 再現方法
ステージ3に入り、クエストを進める。

## 想定される解決策
表記と内容を一致させる。どちらが正しいか不明なため、レベルデザイン担当者による修正が望ましい。

**Comment by 2127002** [comment]
修正完了しています、表記が正しく「2回刺す」が正常な動作となります

**Comment by GTM106** [comment]
修正を確認しました。
