### ISSUE TITLE
ピンチBGM仕様

### ISSUE THREAD

**Issue by Harmony82** [tpu-2022-teamA/Dango#277]
## 仕様内容
ピンチになった時（制限時間残り30秒。一応可変するように）ピンチSEを鳴らす。ピンチSEの再生開始から1秒後にピンチBGMを再生開始ループさせるように。

残りの制限時間が30秒以上になったらピンチBGMを0.1秒でフェードアウト。
フェードアウト完了後、0.3秒後に0.1秒のフェードインで通常BGMを再生開始。ピンチになる前のBGMの再生位置を記憶しておいてそこから再生を再開。

違和感があるようだったら言ってください。

**Comment by GTM106** [comment]
#278 で完了しています。確認前にdevelopに上げてしまったのでそちらで確認お願いします。

**Comment by Harmony82** [comment]
確認しました。
